version: '3.3'

services:
  # web:
  #   container_name: codeigniter-react-nginx
  #   image: nginx:latest
  #   ports:
  #     - '8090:80'
  #   volumes:
  #     - ./:/app
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
      - ./init_sql.sh:/init_sql.sh
    command: --default-authentication-plugin=mysql_native_password
    # entrypoint: sh -c "
    #   echo 'CREATE DATABASE IF NOT EXISTS codeigniter_react_test;' > /docker-entrypoint-initdb.d/init.sql;
    #   /usr/local/bin/docker-entrypoint.sh --default-authentication-plugin=mysql_native_password"
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  php:
    image: php:7.4.20-fpm-alpine3.13
    command: ash -c "apk update && apk add npm php7-mysqli && docker-php-ext-install mysqli && npm install && npm run build && php -S localhost:8087"
    working_dir: /app
    # ports:
    #   - 8087:8087
    volumes:
      - ./:/app
      # - ./php.ini:/etc/php7/php.ini
